import type { AIModel } from '../types';

// All available models with current pricing
export const AVAILABLE_MODELS: AIModel[] = [
  // ── OpenAI ──────────────────────────────────────────
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    contextWindow: 128000,
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
    capabilities: ['chat', 'code', 'vision'],
    recommended: 'worker',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    contextWindow: 128000,
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    capabilities: ['chat', 'code', 'vision'],
    recommended: 'companion',
  },
  {
    id: 'o1',
    name: 'o1 (Reasoning)',
    provider: 'openai',
    contextWindow: 200000,
    inputPricePer1M: 15.0,
    outputPricePer1M: 60.0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
  },
  {
    id: 'o1-mini',
    name: 'o1 Mini',
    provider: 'openai',
    contextWindow: 128000,
    inputPricePer1M: 3.0,
    outputPricePer1M: 12.0,
    capabilities: ['chat', 'code', 'reasoning'],
  },

  // ── Anthropic ───────────────────────────────────────
  {
    id: 'claude-sonnet-4-20250514',
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    contextWindow: 200000,
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    capabilities: ['chat', 'code', 'reasoning', 'vision'],
    recommended: 'worker',
  },
  {
    id: 'claude-3-5-haiku-20241022',
    name: 'Claude 3.5 Haiku',
    provider: 'anthropic',
    contextWindow: 200000,
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.25,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
  },
  {
    id: 'claude-opus-4-20250514',
    name: 'Claude Opus 4',
    provider: 'anthropic',
    contextWindow: 200000,
    inputPricePer1M: 15.0,
    outputPricePer1M: 75.0,
    capabilities: ['chat', 'code', 'reasoning', 'vision'],
    recommended: 'worker',
  },

  // ── Google ──────────────────────────────────────────
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    contextWindow: 1000000,
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    capabilities: ['chat', 'code', 'reasoning', 'vision'],
    recommended: 'worker',
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    provider: 'google',
    contextWindow: 1000000,
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    capabilities: ['chat', 'code', 'vision'],
    recommended: 'companion',
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    contextWindow: 1000000,
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    capabilities: ['chat', 'code', 'vision'],
    recommended: 'companion',
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    contextWindow: 2000000,
    inputPricePer1M: 1.25,
    outputPricePer1M: 5.0,
    capabilities: ['chat', 'code', 'reasoning', 'vision'],
    recommended: 'worker',
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    contextWindow: 1000000,
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
  },

  // ── Groq — ultra-fast inference (LPU) ─────────────
  {
    id: 'llama-3.1-8b-instant',
    name: 'LLaMA 3.1 8B Instant ⚡',
    provider: 'groq',
    contextWindow: 128000,
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.08,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
  },
  {
    id: 'llama-3.3-70b-versatile',
    name: 'LLaMA 3.3 70B Versatile',
    provider: 'groq',
    contextWindow: 128000,
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
  },
  {
    id: 'llama-3.1-70b-versatile',
    name: 'LLaMA 3.1 70B Versatile',
    provider: 'groq',
    contextWindow: 128000,
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'companion',
  },
  {
    id: 'mixtral-8x7b-32768',
    name: 'Mixtral 8x7B',
    provider: 'groq',
    contextWindow: 32768,
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.24,
    capabilities: ['chat', 'code'],
  },
  {
    id: 'gemma2-9b-it',
    name: 'Gemma 2 9B',
    provider: 'groq',
    contextWindow: 8192,
    inputPricePer1M: 0.20,
    outputPricePer1M: 0.20,
    capabilities: ['chat'],
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: 'DeepSeek R1 Distill 70B',
    provider: 'groq',
    contextWindow: 128000,
    inputPricePer1M: 0.75,
    outputPricePer1M: 0.99,
    capabilities: ['chat', 'reasoning'],
    recommended: 'worker',
  },

  // ── Local (Ollama) — free forever ─────────────────
  // ★ = recommended for that brain role

  // Llama family (Meta) — llama3.3 is the newest as of Dec 2024
  {
    id: 'llama3.2:3b',
    name: 'Llama 3.2 3B ⚡',
    provider: 'ollama',
    contextWindow: 128000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'llama3.2',
    name: 'Llama 3.2 (default)',
    provider: 'ollama',
    contextWindow: 128000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'llama3.1:8b',
    name: 'Llama 3.1 8B',
    provider: 'ollama',
    contextWindow: 128000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'llama3.1:70b',
    name: 'Llama 3.1 70B',
    provider: 'ollama',
    contextWindow: 128000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
    local: true,
  },
  {
    id: 'llama3.3:70b',
    name: 'Llama 3.3 70B ★',
    provider: 'ollama',
    contextWindow: 128000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
    local: true,
  },

  // Qwen 2.5 (Alibaba) — excellent all-around, Dec 2024
  {
    id: 'qwen2.5:7b',
    name: 'Qwen 2.5 7B',
    provider: 'ollama',
    contextWindow: 32000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'qwen2.5:14b',
    name: 'Qwen 2.5 14B ★',
    provider: 'ollama',
    contextWindow: 32000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'qwen2.5:32b',
    name: 'Qwen 2.5 32B ★',
    provider: 'ollama',
    contextWindow: 32000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
    local: true,
  },
  {
    id: 'qwen2.5:72b',
    name: 'Qwen 2.5 72B',
    provider: 'ollama',
    contextWindow: 32000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
    local: true,
  },

  // DeepSeek R1 — best free reasoning/coding model family, Jan 2025
  {
    id: 'deepseek-r1:7b',
    name: 'DeepSeek R1 7B',
    provider: 'ollama',
    contextWindow: 32000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'deepseek-r1:14b',
    name: 'DeepSeek R1 14B ★',
    provider: 'ollama',
    contextWindow: 32000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
    local: true,
  },
  {
    id: 'deepseek-r1:32b',
    name: 'DeepSeek R1 32B ★',
    provider: 'ollama',
    contextWindow: 32000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
    local: true,
  },

  // Gemma 2 (Google) — solid, efficient
  {
    id: 'gemma2:9b',
    name: 'Gemma 2 9B',
    provider: 'ollama',
    contextWindow: 8000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'gemma2:27b',
    name: 'Gemma 2 27B',
    provider: 'ollama',
    contextWindow: 8000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
    local: true,
  },

  // Mistral family
  {
    id: 'mistral',
    name: 'Mistral 7B',
    provider: 'ollama',
    contextWindow: 32000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'mistral-nemo',
    name: 'Mistral Nemo 12B',
    provider: 'ollama',
    contextWindow: 128000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code'],
    recommended: 'companion',
    local: true,
  },

  // Phi (Microsoft) — small but punches above weight
  {
    id: 'phi4',
    name: 'Phi-4 14B ★',
    provider: 'ollama',
    contextWindow: 16000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'companion',
    local: true,
  },
  {
    id: 'phi3',
    name: 'Phi-3',
    provider: 'ollama',
    contextWindow: 4000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code'],
    local: true,
  },

  // Code-specialized
  {
    id: 'codellama:34b',
    name: 'CodeLlama 34B',
    provider: 'ollama',
    contextWindow: 16000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['code'],
    recommended: 'worker',
    local: true,
  },

  // ── OpenRouter — 300+ models via single API ───────────
  {
    id: 'openrouter/auto',
    name: 'OpenRouter Auto (routes to best model)',
    provider: 'openrouter',
    contextWindow: 128000,
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'companion',
  },
  {
    id: 'openrouter/anthropic/claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet (via OpenRouter)',
    provider: 'openrouter',
    contextWindow: 200000,
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    capabilities: ['chat', 'code', 'reasoning', 'vision'],
    recommended: 'worker',
  },
  {
    id: 'openrouter/google/gemini-2.0-flash-001',
    name: 'Gemini 2.0 Flash (via OpenRouter)',
    provider: 'openrouter',
    contextWindow: 1000000,
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    capabilities: ['chat', 'code', 'vision'],
    recommended: 'companion',
  },
  {
    id: 'openrouter/meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B Instruct (via OpenRouter)',
    provider: 'openrouter',
    contextWindow: 128000,
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
  },
  {
    id: 'openrouter/mistralai/mistral-large',
    name: 'Mistral Large (via OpenRouter)',
    provider: 'openrouter',
    contextWindow: 128000,
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
  },
  {
    id: 'openrouter/qwen/qwen-2.5-coder-32b-instruct',
    name: 'Qwen 2.5 Coder 32B (via OpenRouter)',
    provider: 'openrouter',
    contextWindow: 32000,
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    capabilities: ['code'],
    recommended: 'worker',
  },
  {
    id: 'openrouter/deepseek/deepseek-r1',
    name: 'DeepSeek R1 (via OpenRouter)',
    provider: 'openrouter',
    contextWindow: 128000,
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    capabilities: ['chat', 'code', 'reasoning'],
    recommended: 'worker',
  },
];

// Provider metadata
export const PROVIDERS = {
  openai: {
    id: 'openai',
    name: 'OpenAI',
    icon: '🟢',
    description: 'GPT-4o, o1, and more. Best general-purpose AI.',
    keyUrl: 'https://platform.openai.com/api-keys',
    keyPrefix: 'sk-',
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    icon: '🟠',
    description: 'Claude models. Excellent for code and long documents.',
    keyUrl: 'https://console.anthropic.com/settings/keys',
    keyPrefix: 'sk-ant-',
  },
  google: {
    id: 'google',
    name: 'Google Gemini',
    icon: '🔵',
    description: 'Gemini 2.0 Flash — best free AI in 2026. 1,500 requests/day free, 1M context, no card needed. Get a key at aistudio.google.com in 30 seconds.',
    keyUrl: 'https://aistudio.google.com/apikey',
    keyPrefix: 'AI',
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    icon: '⚡',
    description: 'Fastest free AI — LPU hardware, sub-500ms responses. llama-3.3-70b + Qwen 2.5 Coder 32B for code. Best for real-time use.',
    keyUrl: 'https://console.groq.com/keys',
    keyPrefix: 'gsk_',
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: '🌐',
    description: 'Access 300+ models through one API. Free tier available. Get a key at openrouter.ai/keys.',
    keyUrl: 'https://openrouter.ai/keys',
    keyPrefix: 'sk-or-',
  },
  runway: {
    id: 'runway',
    name: 'Runway',
    icon: '🎬',
    keyUrl: 'https://app.runwayml.com/settings',
    requiresKey: true,
    keyPrefix: 'rwa_',
    keyPlaceholder: 'rwa_...',
    description: 'State-of-the-art video generation (Gen-3, Gen-4)',
    models: [] as const,
  },
  relay: {
    id: 'relay',
    name: 'Hosted Relay (optional)',
    icon: '🔗',
    description: 'Route requests through any OpenAI-compatible endpoint you control — a self-hosted gateway, a corporate proxy, or a hosted service. Off unless you configure a relay URL.',
    keyUrl: '',
    keyPrefix: '',
    optional: true,
  },
  opencode: {
    id: 'opencode',
    name: 'OpenCode',
    icon: '🧩',
    description:
      'Any model the opencode CLI can reach — its own zen service and OpenRouter — ' +
      'routed through a local loopback bridge. Needs the opencode CLI installed, not an API key here.',
    keyUrl: 'https://opencode.ai',
    keyPrefix: '',
    local: true,
  },
  'opencode-zen': {
    id: 'opencode-zen',
    name: 'OpenCode Zen',
    icon: '✨',
    description:
      "OpenCode Zen — tested models from the OpenCode team, reached through the local opencode " +
      'bridge. Without a key you still get the free Zen models; a key unlocks the rest.',
    keyUrl: 'https://opencode.ai/docs/zen/',
    keyPrefix: '',
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama (Local)',
    icon: '🏠',
    description: 'Run models locally on your machine. Free forever.',
    keyUrl: 'https://ollama.ai',
    keyPrefix: '',
    local: true,
  },
} as const;

export type ProviderId = keyof typeof PROVIDERS;

export function getModelsForProvider(providerId: string): AIModel[] {
  return AVAILABLE_MODELS.filter((m) => m.provider === providerId);
}

export function getModel(modelId: string): AIModel | undefined {
  return AVAILABLE_MODELS.find((m) => m.id === modelId);
}

export function formatPrice(price: number): string {
  if (price === 0) return 'Free';
  if (price < 1) return `$${price.toFixed(3)}`;
  return `$${price.toFixed(2)}`;
}

export function estimateCost(
  modelId: string,
  inputTokens: number,
  outputTokens: number
): number {
  const model = getModel(modelId);
  if (!model) return 0;
  return (
    (inputTokens / 1_000_000) * model.inputPricePer1M +
    (outputTokens / 1_000_000) * model.outputPricePer1M
  );
}
