/**
 * Markdown manifest for Henry export packs — handoff-friendly, honest about inclusion vs references.
 */

import type { ExportBundleModel } from './exportBundle';
import { EXPORT_PATH_HONESTY, getExportPresetMeta } from './exportBundle';

export function buildExportManifestMarkdown(bundle: ExportBundleModel): string {
  const preset = getExportPresetMeta(bundle.preset);
  const lines: string[] = [
    '# Export pack manifest',
    '',
    `**Title:** ${bundle.title}`,
    `**Preset:** ${preset.label}`,
    `**Henry operating mode:** ${bundle.operatingMode}`,
    `**Generated:** ${bundle.createdAt}`,
    `**Generated by:** Henry AI (henry-ai-desktop)`,
    '',
    '> Export packs can include direct artifacts and path-only references; both are labeled clearly.',
    '',
    '## Honesty',
    EXPORT_PATH_HONESTY,
    '',
  ];

  lines.push('## Artifacts');
  lines.push('');
  lines.push('| Label | Path (workspace-relative) | Category | Status | Notes |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const a of bundle.artifacts) {
    const pathCell = a.path ? `\`${a.path}\`` : '—';
    const status =
      a.inclusion === 'included'
        ? a.copiedTo
          ? `Included (copied to \`${a.copiedTo}\`)`
          : 'Included (in manifest text)'
        : 'Referenced (path only)';
    const note = (a.note || '').replace(/\|/g, '\\|');
    lines.push(
      `| ${a.label.replace(/\|/g, '\\|')} | ${pathCell} | ${a.category} | ${status} | ${note || '—'} |`
    );
  }
  lines.push('');

  lines.push('## Related linkage');
  lines.push(
    `- **Conversation ID:** ${bundle.relatedConversationId ?? '_(none)_'}`,
    `- **Related task IDs:** ${
      bundle.relatedTaskIds.length ? bundle.relatedTaskIds.map((id) => `\`${id}\``).join(', ') : '_(none)_'
    }`,
    ''
  );

  if (bundle.userNotes.trim()) {
    lines.push('## Included notes (embedded in this manifest)');
    lines.push('');
    lines.push(bundle.userNotes.trim());
    lines.push('');
  }

  lines.push('---');
  lines.push('*End of manifest*');
  lines.push('');

  return lines.join('\n');
}
